info:
  title: Apimsync API
  version: 0.1.6
openapi: 3.0.0
servers:
  - url: https://apimsync-693189995131.europe-west1.run.app
paths:
  /v1/apim/status:
    get:
      operationId: get-v1-apim-status
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApimStatusBody"
          description: OK
        default:
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/ErrorModel"
          description: Error
      summary: Get v1 apim status
  /v1/apim/sync:
    post:
      operationId: post-v1-apim-sync
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ApimSyncInputBody"
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApimSyncOutputBody"
          description: OK
        default:
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/ErrorModel"
          description: Error
      summary: Post v1 apim sync
components:
  schemas:
    ApimStatusBody:
      properties:
        $schema:
          description: A URL to the JSON Schema for this object.
          format: uri
          readOnly: true
          type: string
        apigee:
          $ref: "#/components/schemas/PlatformStatus"
        apihub:
          $ref: "#/components/schemas/PlatformStatus"
        aws:
          $ref: "#/components/schemas/PlatformStatus"
        azure:
          $ref: "#/components/schemas/PlatformStatus"
      required:
        - apigee
        - apihub
        - azure
        - aws
      type: object
    ApimSyncInputBody:
      additionalProperties: false
      properties:
        $schema:
          description: A URL to the JSON Schema for this object.
          format: uri
          readOnly: true
          type: string
        offramp:
          description: The APIM platform to offramp the APIs from.
          enum:
            - azure
            - aws
          type: string
        onramp:
          description: The APIM platform to onramp the APIs to.
          enum:
            - apihub
          type: string
      required:
        - offramp
        - onramp
      type: object
    ApimSyncOutputBody:
      additionalProperties: false
      properties:
        $schema:
          description: A URL to the JSON Schema for this object.
          format: uri
          readOnly: true
          type: string
        message:
          description: The result of the sync operation.
          type: string
        result:
          description: The result of the sync operation.
          type: boolean
      required:
        - result
        - message
      type: object
    ErrorDetail:
      additionalProperties: false
      properties:
        location:
          description: Where the error occurred, e.g. 'body.items[3].tags' or 'path.thing-id'
          type: string
        message:
          description: Error message text
          type: string
        value:
          description: The value at the given location
      type: object
    ErrorModel:
      additionalProperties: false
      properties:
        $schema:
          description: A URL to the JSON Schema for this object.
          format: uri
          readOnly: true
          type: string
        detail:
          description: A human-readable explanation specific to this occurrence of the problem.
          type: string
        errors:
          description: Optional list of individual error details
          items:
            $ref: "#/components/schemas/ErrorDetail"
          type: array
        instance:
          description: A URI reference that identifies the specific occurrence of the problem.
          format: uri
          type: string
        status:
          description: HTTP status code
          format: int64
          type: integer
        title:
          description: A short, human-readable summary of the problem type. This value should not change between occurrences of the error.
          type: string
        type:
          default: about:blank
          description: A URI reference to human-readable documentation for the error.
          format: uri
          type: string
      type: object
    PlatformStatus:
      additionalProperties: false
      properties:
        connected:
          type: boolean
        message:
          type: string
      required:
        - connected
        - message
      type: object
